#ifndef __UNIFIED_MP3_CONFIG_H__
#define __UNIFIED_MP3_CONFIG_H__

#undef USE_KT403A_PLAYER
#undef USE_WT2003S_PLAYER
//#undef USE_WT2605C_PLAYER
#undef USE_DF_ROBOT_DF_PLAYER_MINI

#endif /* __UNIFIED_MP3_CONFIG_H__ */
